pipeline {
    agent any
    environment {
        // Define environment variables here
    }
    // Define SCM
    options {
        // Global options like timeout, retry, etc.
    }
    triggers {
        // Define triggers like SCM polling
        pollSCM('H */12 * * *') // Polls SCM every 12 hours; 
    }
    stages {
        stage('Checkout') {
            steps {
                // Check out from SCM
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Build') {
            steps {
                // Commands to build your project
                sh 'npm run build' 
            }
        }
        stage('Test') {
            steps {
                // Commands to run your tests
                sh 'npm test'
            }
        }
        stage('Deploy') {
            steps {
                // Commands to deploy your application
                echo 'Deploying..'
                // Example: deployToProd()
            }
        }
    }
    post {
        failure {
            // Actions to take if the pipeline fails
            echo 'The build failed.'
        }
        success {
            // Actions to take if the pipeline succeeds
            echo 'The build was successful.'
        }
    }
}
